//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicManager.Localization {
    using System;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {

        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() { }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClinicManager.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        public static string Dashboard => ResourceManager.GetString("Dashboard", resourceCulture) ?? "Dashboard";
        public static string Patients => ResourceManager.GetString("Patients", resourceCulture) ?? "Patients";
        public static string Appointments => ResourceManager.GetString("Appointments", resourceCulture) ?? "Appointments";
        public static string Billing => ResourceManager.GetString("Billing", resourceCulture) ?? "Billing";
        public static string MedicalRecords => ResourceManager.GetString("MedicalRecords", resourceCulture) ?? "Medical Records";
        public static string Settings => ResourceManager.GetString("Settings", resourceCulture) ?? "Settings";
        public static string Search => ResourceManager.GetString("Search", resourceCulture) ?? "Search";
        public static string Add => ResourceManager.GetString("Add", resourceCulture) ?? "Add";
        public static string Edit => ResourceManager.GetString("Edit", resourceCulture) ?? "Edit";
        public static string Delete => ResourceManager.GetString("Delete", resourceCulture) ?? "Delete";
        public static string Save => ResourceManager.GetString("Save", resourceCulture) ?? "Save";
        public static string Cancel => ResourceManager.GetString("Cancel", resourceCulture) ?? "Cancel";
        public static string Close => ResourceManager.GetString("Close", resourceCulture) ?? "Close";
        public static string Export => ResourceManager.GetString("Export", resourceCulture) ?? "Export";
        public static string Confirm => ResourceManager.GetString("Confirm", resourceCulture) ?? "Confirm";
        public static string ConfirmDelete => ResourceManager.GetString("ConfirmDelete", resourceCulture) ?? "Are you sure you want to delete this item?";
        public static string ConfirmDeletePatient => ResourceManager.GetString("ConfirmDeletePatient", resourceCulture) ?? "Are you sure you want to delete this patient?";
        public static string Success => ResourceManager.GetString("Success", resourceCulture) ?? "Success";
        public static string Error => ResourceManager.GetString("Error", resourceCulture) ?? "Error";
        public static string Warning => ResourceManager.GetString("Warning", resourceCulture) ?? "Warning";
        public static string SavedSuccessfully => ResourceManager.GetString("SavedSuccessfully", resourceCulture) ?? "Saved successfully";
        public static string DeletedSuccessfully => ResourceManager.GetString("DeletedSuccessfully", resourceCulture) ?? "Deleted successfully";
        public static string BackupCreated => ResourceManager.GetString("BackupCreated", resourceCulture) ?? "Backup created successfully";
        public static string BackupRestored => ResourceManager.GetString("BackupRestored", resourceCulture) ?? "Backup restored successfully";
        public static string ExportComplete => ResourceManager.GetString("ExportComplete", resourceCulture) ?? "Export completed successfully";
        public static string InvalidLicense => ResourceManager.GetString("InvalidLicense", resourceCulture) ?? "Invalid license key";
        public static string LicenseActivated => ResourceManager.GetString("LicenseActivated", resourceCulture) ?? "License activated successfully!";
        public static string Validation => ResourceManager.GetString("Validation", resourceCulture) ?? "Validation";
        public static string NotFound => ResourceManager.GetString("NotFound", resourceCulture) ?? "Not Found";
        public static string SelectPatientRequired => ResourceManager.GetString("SelectPatientRequired", resourceCulture) ?? "Please select a patient first.";
        public static string PatientNameRequired => ResourceManager.GetString("PatientNameRequired", resourceCulture) ?? "Patient name is required.";
        public static string DoctorRequired => ResourceManager.GetString("DoctorRequired", resourceCulture) ?? "Doctor name is required.";
        public static string InvalidTimeFormat => ResourceManager.GetString("InvalidTimeFormat", resourceCulture) ?? "Please enter time in HH:mm format (e.g. 09:30).";
        public static string NoAppointmentsInRange => ResourceManager.GetString("NoAppointmentsInRange", resourceCulture) ?? "No appointments found for the selected date range.";
        public static string NoPatients => ResourceManager.GetString("NoPatients", resourceCulture) ?? "No patients found. Add patients first.";
    }
}
